name: hexlet-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      run:
        make lint